apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    name: webapp
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000
      protocol: TCP
  selector:
    name: webapp